// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-3mG7SEQrLYE-VW0QGh6HZ6US0NN_bE',
    appId: '1:116488014780:web:eea20a74143ed18ffa39b9',
    messagingSenderId: '116488014780',
    projectId: 'ecosphere-43c82',
    authDomain: 'ecosphere-43c82.firebaseapp.com',
    storageBucket: 'ecosphere-43c82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNHLsKmbGBSCc273BzqOmWS7ZYnAw35U',
    appId: '1:116488014780:android:6f412febc5faab93fa39b9',
    messagingSenderId: '116488014780',
    projectId: 'ecosphere-43c82',
    storageBucket: 'ecosphere-43c82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EJ_mx2ALGCEuB63pLSpAA1h1dlA9jK0',
    appId: '1:116488014780:ios:0214fc20152ebdb7fa39b9',
    messagingSenderId: '116488014780',
    projectId: 'ecosphere-43c82',
    storageBucket: 'ecosphere-43c82.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

}